"""Generates ansible/inventories/<environment>/hosts.yml from a fresh
`terraform output -json` dump: reads the app Auto Scaling Group name,
asks AWS which instances are currently InService, and writes them out
in the shape documented by
ansible/inventories/dev/hosts.yml.example.

This is the pipeline's bridge between "Terraform just created/changed
infrastructure" and "Ansible has a concrete list of hosts to configure" —
invoked by shared-library/vars/inventoryGeneration.groovy right after
terraform apply.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

from cloudforge.common import get_boto3_session, load_json_file, setup_logging, terraform_output_value


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment", required=True)
    parser.add_argument("--region", required=True)
    parser.add_argument("--tf-outputs", required=True, help="Path to a `terraform output -json` dump")
    parser.add_argument("--output", required=True, help="Path to write the generated hosts.yml")
    parser.add_argument("-v", "--verbose", action="store_true")
    return parser.parse_args(argv)


def get_in_service_instance_ids(asg_client: Any, asg_name: str) -> list[str]:
    response = asg_client.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])
    groups = response.get("AutoScalingGroups", [])
    if not groups:
        raise ValueError(f"Auto Scaling Group '{asg_name}' not found")

    return [
        instance["InstanceId"]
        for instance in groups[0].get("Instances", [])
        if instance.get("LifecycleState") == "InService"
    ]


def describe_hosts(ec2_client: Any, instance_ids: list[str]) -> dict[str, dict]:
    if not instance_ids:
        return {}

    hosts: dict[str, dict] = {}
    paginator = ec2_client.get_paginator("describe_instances")
    for page in paginator.paginate(InstanceIds=instance_ids):
        for reservation in page["Reservations"]:
            for instance in reservation["Instances"]:
                if instance["State"]["Name"] != "running":
                    continue
                instance_id = instance["InstanceId"]
                hosts[instance_id] = {
                    "ansible_host": instance["PrivateIpAddress"],
                    "private_ip": instance["PrivateIpAddress"],
                    "instance_id": instance_id,
                    "availability_zone": instance["Placement"]["AvailabilityZone"],
                }
    return hosts


def build_inventory(hosts: dict[str, dict], ssm_transfer_bucket_name: str) -> dict:
    return {
        "all": {
            "vars": {"ansible_aws_ssm_bucket_name": ssm_transfer_bucket_name},
            "children": {"app": {"hosts": hosts}},
        }
    }


def write_inventory(inventory: dict, output_path: str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Generated by python/cloudforge/inventory/dynamic_inventory.py — do not edit by hand.\n")
        yaml.safe_dump(inventory, f, default_flow_style=False, sort_keys=False)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    logger = setup_logging(args.verbose)

    try:
        outputs = load_json_file(args.tf_outputs)
        asg_name = terraform_output_value(outputs, "autoscaling_group_name")
        # community.aws.aws_ssm stages files through S3 (SSM has no native
        # file-transfer channel); the app's own data bucket already grants
        # the instance role read/write access, so reuse it instead of
        # standing up a bucket dedicated to this.
        ssm_transfer_bucket_name = terraform_output_value(outputs, "app_data_bucket_name")
    except (FileNotFoundError, ValueError, KeyError) as exc:
        logger.error(str(exc))
        return 1

    session = get_boto3_session(args.region)
    asg_client = session.client("autoscaling")
    ec2_client = session.client("ec2")

    try:
        instance_ids = get_in_service_instance_ids(asg_client, asg_name)
    except ValueError as exc:
        logger.error(str(exc))
        return 1

    if not instance_ids:
        logger.error(
            "Auto Scaling Group '%s' has zero InService instances. Refusing to write an "
            "empty inventory — check the ASG's activity history for launch failures.",
            asg_name,
        )
        return 1

    hosts = describe_hosts(ec2_client, instance_ids)
    if len(hosts) != len(instance_ids):
        logger.warning(
            "%d InService instance(s) reported by the ASG, but only %d are actually 'running' "
            "in EC2 — the rest are likely still launching.",
            len(instance_ids),
            len(hosts),
        )

    inventory = build_inventory(hosts, ssm_transfer_bucket_name)
    write_inventory(inventory, args.output)
    logger.info("Wrote %d host(s) for environment '%s' to %s", len(hosts), args.environment, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
